//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BmiReport", Namespace="http://www.beetledev.com")]
    public partial class BmiReport : object
    {
        
        private double BmiValueField;
        
        private string BmiDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double BmiValue
        {
            get
            {
                return this.BmiValueField;
            }
            set
            {
                this.BmiValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BmiDesc
        {
            get
            {
                return this.BmiDescField;
            }
            set
            {
                this.BmiDescField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.beetledev.com", ConfigurationName="ServiceReference1.BmiServiceSoap")]
    public interface BmiServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beetledev.com/getBmiReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getBmiReportResponse> getBmiReportAsync(ServiceReference1.getBmiReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beetledev.com/getBmiValue", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getBmiValueAsync(double w, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beetledev.com/getBmiDesc", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getBmiDescResponse> getBmiDescAsync(ServiceReference1.getBmiDescRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBmiReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBmiReport", Namespace="http://www.beetledev.com", Order=0)]
        public ServiceReference1.getBmiReportRequestBody Body;
        
        public getBmiReportRequest()
        {
        }
        
        public getBmiReportRequest(ServiceReference1.getBmiReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beetledev.com")]
    public partial class getBmiReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double w;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double h;
        
        public getBmiReportRequestBody()
        {
        }
        
        public getBmiReportRequestBody(double w, double h)
        {
            this.w = w;
            this.h = h;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBmiReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBmiReportResponse", Namespace="http://www.beetledev.com", Order=0)]
        public ServiceReference1.getBmiReportResponseBody Body;
        
        public getBmiReportResponse()
        {
        }
        
        public getBmiReportResponse(ServiceReference1.getBmiReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beetledev.com")]
    public partial class getBmiReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.BmiReport getBmiReportResult;
        
        public getBmiReportResponseBody()
        {
        }
        
        public getBmiReportResponseBody(ServiceReference1.BmiReport getBmiReportResult)
        {
            this.getBmiReportResult = getBmiReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBmiDescRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBmiDesc", Namespace="http://www.beetledev.com", Order=0)]
        public ServiceReference1.getBmiDescRequestBody Body;
        
        public getBmiDescRequest()
        {
        }
        
        public getBmiDescRequest(ServiceReference1.getBmiDescRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beetledev.com")]
    public partial class getBmiDescRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double bmi;
        
        public getBmiDescRequestBody()
        {
        }
        
        public getBmiDescRequestBody(double bmi)
        {
            this.bmi = bmi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBmiDescResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBmiDescResponse", Namespace="http://www.beetledev.com", Order=0)]
        public ServiceReference1.getBmiDescResponseBody Body;
        
        public getBmiDescResponse()
        {
        }
        
        public getBmiDescResponse(ServiceReference1.getBmiDescResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beetledev.com")]
    public partial class getBmiDescResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getBmiDescResult;
        
        public getBmiDescResponseBody()
        {
        }
        
        public getBmiDescResponseBody(string getBmiDescResult)
        {
            this.getBmiDescResult = getBmiDescResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface BmiServiceSoapChannel : ServiceReference1.BmiServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class BmiServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.BmiServiceSoap>, ServiceReference1.BmiServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BmiServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BmiServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), BmiServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BmiServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BmiServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BmiServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BmiServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BmiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getBmiReportResponse> ServiceReference1.BmiServiceSoap.getBmiReportAsync(ServiceReference1.getBmiReportRequest request)
        {
            return base.Channel.getBmiReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getBmiReportResponse> getBmiReportAsync(double w, double h)
        {
            ServiceReference1.getBmiReportRequest inValue = new ServiceReference1.getBmiReportRequest();
            inValue.Body = new ServiceReference1.getBmiReportRequestBody();
            inValue.Body.w = w;
            inValue.Body.h = h;
            return ((ServiceReference1.BmiServiceSoap)(this)).getBmiReportAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<double> getBmiValueAsync(double w, double h)
        {
            return base.Channel.getBmiValueAsync(w, h);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getBmiDescResponse> ServiceReference1.BmiServiceSoap.getBmiDescAsync(ServiceReference1.getBmiDescRequest request)
        {
            return base.Channel.getBmiDescAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getBmiDescResponse> getBmiDescAsync(double bmi)
        {
            ServiceReference1.getBmiDescRequest inValue = new ServiceReference1.getBmiDescRequest();
            inValue.Body = new ServiceReference1.getBmiDescRequestBody();
            inValue.Body.bmi = bmi;
            return ((ServiceReference1.BmiServiceSoap)(this)).getBmiDescAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BmiServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BmiServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BmiServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.beetledev.com/webservices/bmiservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BmiServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.beetledev.com/webservices/bmiservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BmiServiceSoap,
            
            BmiServiceSoap12,
        }
    }
}
